info:
  setting: ''
  description: 'semi_REFUGE100+REFUGE700'
MODEL:
  sup: False
  retraining: True
  uda_tgt_label: False
  NUM_CLASSES: 2
  batch_size: 8
  epochs: 100
  lr: 0.002 # 0.004/16*batch_size
  crop_size: 512
  dataset: 'semi'
  data_root: './data/fundus_datasets/od_oc/WACV/REFUGE_cross_new/'
  backbone: 'resnet50'
  model: 'deeplabv3plus'
  stage1: False
  stage2_ckpt_path: 'experiments/domain_shift_semi/1_7/uda1/G1R7R4_semi_Pretrained_prototype_multi_prototype/ckpt/val_OD_IoU=0.850376-val_mIoU=0.850376-val_OD_dice_score=0.958925-val_mDice=0.958925-val_OC_dice_score=0.000000-val_OC_IoU=0.000000.ckpt'


dataset:
    target: segment.dataloader.DataModuleFromConfig
    params:
        batch_size: 16
        num_workers: 8
        train:
            target: segment.dataloader.od_oc_dataset.SupTrain
            params:
                task: 'od'
                name: 'semi'
                root: './data/fundus_datasets/od_oc/WACV/REFUGE_cross_new/'
                unlabeled_id_path: 'dataset/sup/REFUGE700_labeled.txt'
                size: 512
                mode: 'src_tgt_train'


        validation:
            target: segment.dataloader.od_oc_dataset.SupTrain
            params:
                task: 'od'
                name: 'semi'
                root: './data/fundus_datasets/od_oc/WACV/REFUGE_cross_new/'
                size: 512
                mode: 'val'