MODEL:
  backbone: 'resnet50'
  model: 'deeplabv3plus'
  label: True
  uda_pretrained: False
  NUM_CLASSES: 3
  epochs: 300
  lr: 0.002 # 0.004/16*batch_size
  stage1_ckpt_path: 'experiments/SEG/cropped_sup512x512/random1_ODOC_sup10_DCBDFCLoss/ckpt/epoch=445-val_OD_dice=0.920649.ckpt'
  CBL_loss: True
  loss:
    target: torch.nn.CrossEntropyLoss

dataset:
    target: segment.dataloader.DataModuleFromConfig
    params:
        batch_size: 14
        num_workers: 8
        train:
            target: segment.dataloader.od_oc_dataset.SupTrain
            params:
                task: 'od_oc'
                name: 'SEG/cropped_semi/random1/10'
                root: './data/fundus_datasets/od_oc/SEG/'
                labeled_id_path: 'dataset/SEG/cropped_semi/random1/10/labeled.txt'
                unlabeled_id_path: 'dataset/SEG/cropped_semi/random1/10/unlabeled.txt'
                add_unlabeled_id_path: 'dataset/add/705ACRIMA_G1020.txt'
                size: 512
                mode: 'semi_train'
                aug:
                  strong:
                    Not: False
                    default: True
                    ColorJitter: False
                    RandomGrayscale: False
                    blur: False
                    cutout: False
        train2:
          target: segment.dataloader.od_oc_dataset.SupTrain
          params:
            task: 'od_oc'
            name: 'SEG/cropped_semi/random1/10'
            root: './data/fundus_datasets/od_oc/SEG/'
            labeled_id_path: 'dataset/SEG/cropped_semi/random1/10/labeled.txt'
            unlabeled_id_path: 'dataset/SEG/cropped_semi/random1/10/unlabeled.txt'
            add_unlabeled_id_path: 'dataset/add/705ACRIMA_G1020.txt'
            size: 512
            mode: 'semi_train'
            aug:
                strong:
                  default: True
                  ColorJitter: False
                  RandomGrayscale: False
                  blur: False
                  cutout: False
        validation:
            target: segment.dataloader.od_oc_dataset.SupTrain
            params:
                task: 'od_oc'
                name: 'SEG/cropped_semi/random1'
                root: './data/fundus_datasets/od_oc/SEG/'
                size: 512
                mode: 'val'
        test:
            target: segment.dataloader.od_oc_dataset.SupTrain
            params:
              task: 'od_oc'
              name: 'SEG/sup/random1'
              root: './data/fundus_datasets/od_oc/SEG/'
              size: 512
              mode: 'test'