MODEL:
  backbone: 'resnet50'
  model: 'deeplabv3plus'
  label: True
  NUM_CLASSES: 3
  epochs: 200
  lr: 0.001 # 0.004/16*batch_size
  stage1_ckpt_path: 'experiments/SEG/cropped_sup/random1_ODOC_sup90/ckpt/val_OD_dice=0.958672.ckpt'
  loss:
    target: torch.nn.CrossEntropyLoss

dataset:
    target: segment.dataloader.DataModuleFromConfig
    params:
        batch_size: 16
        num_workers: 16
        train:
            target: segment.dataloader.od_oc_dataset.SupTrain
            params:
                task: 'od_oc'
                name: 'SEG/cropped_semi/random1/90'
                root: './data/fundus_datasets/od_oc/SEG/'
                labeled_id_path: 'dataset/SEG/cropped_semi/random1/90/labeled.txt'
                unlabeled_id_path: 'dataset/SEG/cropped_semi/random1/90/unlabeled.txt'
                size: 512
                mode: 'train'
                aug:
                  strong:
                    Not: False
                    default: True
                    ColorJitter: False
                    RandomGrayscale: False
                    blur: False
                    cutout: False
        train2:
          target: segment.dataloader.od_oc_dataset.SupTrain
          params:
            task: 'od_oc'
            name: 'SEG/cropped_semi/random1/90'
            root: './data/fundus_datasets/od_oc/SEG/'
            labeled_id_path: 'dataset/SEG/cropped_semi/random1/90/labeled.txt'
            unlabeled_id_path: 'dataset/SEG/cropped_semi/random1/90/unlabeled.txt'
            size: 512
            mode: 'semi_train'
            aug:
              strong:
                Not: False
                default: True
                ColorJitter: False
                RandomGrayscale: False
                blur: False
                cutout: False
        validation:
            target: segment.dataloader.od_oc_dataset.SupTrain
            params:
                task: 'od_oc'
                name: 'SEG/cropped_semi/random1'
                root: './data/fundus_datasets/od_oc/SEG/'
                size: 512
                mode: 'val'
        test:
            target: segment.dataloader.od_oc_dataset.SupTrain
            params:
              task: 'od_oc'
              name: 'SEG/sup/random1'
              root: './data/fundus_datasets/od_oc/SEG/'
              size: 512
              mode: 'test'