MODEL:
  backbone: 'resnet34'
  model: 'deeplabv3plus'
  NUM_CLASSES: 3
  epochs: 200
  lr: 0.001 # 0.004/16*batch_size
  logitsTransform: True
  loss:
    target: segment.losses.grw_cross_entropy_loss.GRWCrossEntropyLoss
    params:
      num_classes: 3
      class_weight: 'dataset/SEG/whole_cropped_class_weight.txt'
      exp_scale: 0.3

dataset:
    target: segment.dataloader.DataModuleFromConfig
    params:
        batch_size: 8
        num_workers: 7
        train:
            target: segment.dataloader.od_oc_dataset.SupTrain
            params:
                task: 'od_oc'
                name: 'cropped_sup/random1'
                root: './data/fundus_datasets/od_oc/SEG/'
                labeled_id_path: 'dataset/SEG/cropped_sup/random1/training.txt'
                size: 512
                mode: 'train'

        validation:
            target: segment.dataloader.od_oc_dataset.SupTrain
            params:
                task: 'od_oc'
                name: 'SEG/cropped_sup/random1'
                root: './data/fundus_datasets/od_oc/SEG/'
                size: 512
                mode: 'val'
        test:
            target: segment.dataloader.od_oc_dataset.SupTrain
            params:
              task: 'od_oc'
              name: 'SEG/cropped_sup/random1'
              root: './data/fundus_datasets/od_oc/SEG/'
              size: 512
              mode: 'test'