MODEL:
  sup: False
  NUM_CLASSES: 3
  epochs: 200
  lr: 0.002
  crop_size: 512
  backbone: 'resnet50'
  model: 'deeplabv3plus'
  loss:
    target: torch.nn.CrossEntropyLoss


dataset:
    target: segment.dataloader.DataModuleFromConfig
    params:
        batch_size: 16
        num_workers: 8
        train:
            target: segment.dataloader.od_oc_dataset.SupTrain
            params:
                task: 'od_oc'
                name: 'REFUGE/cropped'
                root: './data/fundus_datasets/od_oc/SEG/'
                labeled_id_path: 'dataset/REFUGE/cropped_sup/training.txt'
                size: 512
                mode: 'train'

        validation:
            target: segment.dataloader.od_oc_dataset.SupTrain
            params:
                task: 'od_oc'
                name: 'Drishti-GS/cropped'
                root: './data/fundus_datasets/od_oc/SEG/'
                size: 512
                mode: 'val'
