info:
  setting: 'od_val_refuge/1_7/100gamma'
  description: 'sup'
MODEL:
  sup: True
  NUM_CLASSES: 2
  batch_size: 8
  lr: 0.002 # 0.004/16*batch_size
  epochs: 100
  crop_size: 512
  dataset: 'sup'
  data_root: './data/fundus_datasets/od_oc/WACV/REFUGE_cross_new/'
  backbone: 'resnet50'
  model: 'deeplabv3plus'
  labeled_id_path: 'dataset/splits/sup/REFUGE800_labeled.txt'
  save_path: 'experiments/REFUGE800_sup/models'

dataset:
    target: segment.dataloader.DataModuleFromConfig
    params:
        batch_size: 8
#        num_workers: 8
        train:
            target: segment.dataloader.od_oc_dataset.SupTrain
            params:
                task: 'od'
                name: 'sup'
                root: './data/fundus_datasets/od_oc/WACV/REFUGE_cross_new/'
                labeled_id_path: 'dataset/sup/REFUGE800_labeled.txt'
                size: 512
                mode: 'train'

        validation:
            target: segment.dataloader.od_oc_dataset.SupTrain
            params:
                task: 'od'
                name: 'sup'
                root: './data/fundus_datasets/od_oc/WACV/REFUGE_cross_new/'
                size: 512
                mode: 'val'