info:
  setting: 'od_val_refuge/1_7/100gamma'
  description: 'sup_100GAMMA'
MODEL:
  sup: False
  label: True
  NUM_CLASSES: 3
  epochs: 100
  lr: 0.004 # 0.004/16*batch_size
  crop_size: 512
  task: 'od'
  data_root: './data/fundus_datasets/od_oc/WACV/REFUGE_cross_new/'
  backbone: 'resnet50'
  model: 'deeplabv3plus'
  stage1_ckpt_path: 'experiments/SEG/sup/random1_ODOC_sup90/ckpt/val_mIoU=0.783090-val_mDice=0.938657-val_OD_dice_score=0.938609-val_OD_IoU=0.783561-val_OC_dice_score=0.938706-val_OC_IoU=0.782619.ckpt'


dataset:
    target: segment.dataloader.DataModuleFromConfig
    params:
        batch_size: 16
        num_workers: 8
        train:
            target: segment.dataloader.od_oc_dataset.SupTrain
            params:
                task: 'od_oc'
                name: 'SEG/semi/90'
                root: './data/fundus_datasets/od_oc/SEG/'
                labeled_id_path: 'dataset/SEG/semi/90/random1/labeled.txt'
                unlabeled_id_path: 'dataset/SEG/semi/90/random1/unlabeled.txt'
                size: 512
                mode: 'train'
                aug:
                  strong:
                    Not: False
                    default: True
                    ColorJitter: False
                    RandomGrayscale: False
                    blur: False
                    cutout: False
        train2:
          target: segment.dataloader.od_oc_dataset.SupTrain
          params:
            task: 'od_oc'
            name: 'SEG/semi/90'
            root: './data/fundus_datasets/od_oc/SEG/'
            labeled_id_path: 'dataset/SEG/semi/90/random1/labeled.txt'
            unlabeled_id_path: 'dataset/SEG/semi/90/random1/unlabeled.txt'
            size: 512
            mode: 'semi_train'
            aug:
              strong:
                Not: False
                default: True
                ColorJitter: False
                RandomGrayscale: False
                blur: False
                cutout: False
        validation:
            target: segment.dataloader.od_oc_dataset.SupTrain
            params:
                task: 'od_oc'
                name: 'SEG/semi/90/random1'
                root: './data/fundus_datasets/od_oc/SEG/'
                size: 512
                mode: 'val'
        test:
            target: segment.dataloader.od_oc_dataset.SupTrain
            params:
              task: 'od_oc'
              name: 'SEG/sup/random1'
              root: './data/fundus_datasets/od_oc/SEG/'
              size: 512
              mode: 'test'