MODEL:
  sup: False
  NUM_CLASSES: 3
  epochs: 200
  lr: 0.000174 # 0.004/16*batch_size
  backbone: 'b2'
  backbone_pretrained: True
  model: 'SegFormer'
  optimizer: 'AdamW'
  Attention: 'subv4'
  DC_loss: True
  BD_loss: True
  FC_loss: True
  loss:
    target: torch.nn.CrossEntropyLoss


dataset:
    target: segment.dataloader.DataModuleFromConfig
    params:
        batch_size: 8
        num_workers: 8
        train:
            target: segment.dataloader.od_oc_dataset.SupTrain
            params:
                task: 'od_oc'
                name: 'cropped_sup'
                root: './data/fundus_datasets/od_oc/Drishti-GS/'
                labeled_id_path: 'dataset/Drishti-GS/cropped_sup/training.txt'
                size: 256
                mode: 'train'
                aug:
                  weak:
                    flip: True
                    rotate: True
                    translate: True
                    noise: True
                    scale: True
                    cutout: True

        validation:
            target: segment.dataloader.od_oc_dataset.SupTrain
            params:
                task: 'od_oc'
                name: 'Drishti-GS/cropped_sup'
                root: './data/fundus_datasets/od_oc/Drishti-GS/'
                size: 256
                mode: 'val'
        test:
            target: segment.dataloader.od_oc_dataset.SupTrain
            params:
              task: 'od_oc'
              name: 'Drishti-GS/cropped_sup'
              root: './data/fundus_datasets/od_oc/Drishti-GS/'
              size: 256
              mode: 'test'