info:
  setting: ''
  description: 'semi_GAMMA100+REFUGE700'
aug:
  strong:
    default: False
    ColorJitter: True
    RandomGrayscale: True
MODEL:
  sup: False
  NUM_CLASSES: 2
  batch_size: 8
  epochs: 100
  lr: 0.002 # 0.004/16*batch_size
  crop_size: 512
  dataset: 'semi'
  data_root: './data/fundus_datasets/od_oc/WACV/REFUGE_cross_new/'
  backbone: 'resnet50'
  model: 'deeplabv3plus'
  labeled_id_path: 'dataset/splits/semi/GAMMA100_labeled.txt'
  unlabeled_id_path: 'dataset/splits/semi/REFUGE700_unlabeled.txt'
  pseudo_mask_path: 'experiments/domain_shift_semi/G1R7R4_semi/pseudo_masks'
  logs_path: 'experiments/semi/strong/G1R7R4_CJ_RG_semi/logs'
  save_path: 'experiments/semi/strong/G1R7R4_CJ_RG_semi/models'
  stage1: False
  stage1_ckpt_path: 'experiments/sup/GAMMA100_sup/models/train_mIoUTdeeplabv3plus_resnet50_93.67.pth'
  stage2: False
  stage3: False
  stage4: True
  stage5: False

dataset:
    target: segment.dataloader.DataModuleFromConfig
    params:
        batch_size: 8
        num_workers: 8

        train:
            target: segment.dataloader.od_oc_dataset.SemiTrain
            params:
                task: 'od'
                name: 'semi'
                root: './data/fundus_datasets/od_oc/WACV/REFUGE_cross_new/'
                labeled_id_path: 'dataset/semi/GAMMA100_labeled.txt'
                unlabeled_id_path: 'dataset/semi/REFUGE700_unlabeled.txt'
                size: 512
                mode: 'train'

        validation:
            target: segment.dataloader.od_oc_dataset.SupTrain
            params:
                task: 'od'
                name: 'semi'
                root: './data/fundus_datasets/od_oc/WACV/REFUGE_cross_new/'
                size: 512
                mode: 'val'