info:
  setting: 'od_val_refuge/1_7/100gamma'
  description: 'sup_100GAMMA'
MODEL:
  sup: False
  NUM_CLASSES: 3
  epochs: 100
  lr: 0.004 # 0.004/16*batch_size
  crop_size: 512
  align_loss: 0.3
  class_weight: 'dataset/SEG/whole_class_weight.txt'
  dataset: 'sup'
  data_root: './data/fundus_datasets/od_oc/WACV/REFUGE_cross_new/'
  backbone: 'resnet50'
  model: 'deeplabv3plus'
  labeled_id_path: 'dataset/splits/sup/GAMMA100_labeled.txt'

  save_path: 'experiments/sup/GAMMA100_sup/models'

dataset:
    target: segment.dataloader.DataModuleFromConfig
    params:
        batch_size: 16
        num_workers: 8
        train:
            target: segment.dataloader.od_oc_dataset.SupTrain
            params:
                task: 'od_oc'
                name: 'sup/random1'
                root: './data/fundus_datasets/od_oc/SEG/'
                labeled_id_path: 'dataset/SEG/sup/random1/training.txt'
                size: 512
                mode: 'train'

        validation:
            target: segment.dataloader.od_oc_dataset.SupTrain
            params:
                task: 'od_oc'
                name: 'SEG/sup/random1'
                root: './data/fundus_datasets/od_oc/SEG/'
                size: 512
                mode: 'val'
        test:
            target: segment.dataloader.od_oc_dataset.SupTrain
            params:
              task: 'od_oc'
              name: 'SEG/sup/random1'
              root: './data/fundus_datasets/od_oc/SEG/'
              size: 512
              mode: 'test'