MODEL:
  sup: False
  NUM_CLASSES: 3
  epochs: 200
  lr: 0.01 # 0.004/16*batch_size
  model: 'unet'
  DC_loss: True
  BD_loss: True
  FC_loss: True
  loss:
    target: torch.nn.CrossEntropyLoss


dataset:
    target: segment.dataloader.DataModuleFromConfig
    params:
        batch_size: 16
        num_workers: 4
        train:
            target: segment.dataloader.od_oc_dataset.SupTrain
            params:
                task: 'od_oc'
                name: 'cropped_sup'
                root: './data/fundus_datasets/od_oc/REFUGE/'
                labeled_id_path: 'dataset/REFUGE/cropped_sup/training.txt'
                size: 256
                mode: 'train'

        validation:
            target: segment.dataloader.od_oc_dataset.SupTrain
            params:
                task: 'od_oc'
                name: 'REFUGE/cropped_sup'
                root: './data/fundus_datasets/od_oc/REFUGE/'
                size: 256
                mode: 'val'
        test:
            target: segment.dataloader.od_oc_dataset.SupTrain
            params:
              task: 'od_oc'
              name: 'REFUGE/cropped_sup'
              root: './data/fundus_datasets/od_oc/REFUGE/'
              size: 256
              mode: 'test'