MODEL:
  sup: False
  NUM_CLASSES: 3
  epochs: 200
  BlvLoss: True
  lr: 0.001 # 0.004/16*batch_size
  backbone: 'resnet50'
  model: 'deeplabv3plus'
  loss:
    target: torch.nn.CrossEntropyLoss
#    target: segment.losses.blv_loss.BlvLoss
#    params:
#      cls_num_list: [200482,42736,18925]
#      sigma: 4



dataset:
    target: segment.dataloader.DataModuleFromConfig
    params:
        batch_size: 8
        num_workers: 4
        train:
            target: segment.dataloader.od_oc_dataset.SupTrain
            params:
                task: 'od_oc'
                name: 'cropped_sup/random1'
                root: './data/fundus_datasets/od_oc/SEG/'
                labeled_id_path: 'dataset/SEG/cropped_sup/random1/training.txt'
                size: 512
                mode: 'train'

        validation:
            target: segment.dataloader.od_oc_dataset.SupTrain
            params:
                task: 'od_oc'
                name: 'SEG/cropped_sup/random1'
                root: './data/fundus_datasets/od_oc/SEG/'
                size: 512
                mode: 'val'
        test:
            target: segment.dataloader.od_oc_dataset.SupTrain
            params:
              task: 'od_oc'
              name: 'SEG/cropped_sup/random1'
              root: './data/fundus_datasets/od_oc/SEG/'
              size: 512
              mode: 'test'